#!/bin/bash

help () {
	echo "Usage: $0 []"
}

if [ $# -eq 1 ]
then
        if [ $1 == "--help" ]
        then
                help
	elif [ $1 == "list" ]
	then
		curl https://api.telegram.org/bot194775296:AAFP1mDOYa9EI3itc0PQ4ZyhF0oPCYgc0Dk/getUpdates
        else
		help
        fi
else
	help
fi

