#!/bin/bash
GETTEXT='gettext -d shellegram'

help () {
	USAGE=$($GETTEXT "Usage")
	echo "$USAGE : $0 ( list | msg chat_id text)"
}

if [ $# -eq 1 ]
then
        if [ $1 == "--help" ]
        then
                help
	elif [ $1 == "list" ]
	then
		AVAILABLE=$($GETTEXT "Available IDs to chat")
		echo $AVAILABLE
		curl -s https://api.telegram.org/bot194775296:AAFP1mDOYa9EI3itc0PQ4ZyhF0oPCYgc0Dk/getUpdates | grep -Po '(?<="id":)[0-9]+' | sort | uniq
	else
		help
        fi

elif [ $# -eq 3 ]
	then
        if [ \( $1 == "msg" \) -o \( "$2" -eq "$2" 2>/dev/null \) ]
        then
		curl --silent -X GET --data "chat_id=$2&text=$3"  https://api.telegram.org/bot194775296:AAFP1mDOYa9EI3itc0PQ4ZyhF0oPCYgc0Dk/sendMessage
        else
		INVALID=$($GETTEXT "Invalid command")
		echo $INVALID
        help
        fi

else
	help
fi

