#!/bin/bash


SHELLEGRAM=shellegram

GETTEXT='gettext -d shellegram_ui'
NETWORK=$($GETTEXT "You must set HOST and PORT")
if [ $# -ge 1 ]
then
        if [ $1 -a $2 ]
        then 
                SHELLEGRAM="nc $1 $2"
        else
                echo "You must set HOST and PORT"
                exit -2
        fi
fi

DIALOG=dialog
GETTEXT='gettext -d shellegram_ui'
LIST=$($GETTEXT "List available chats")
MSG=$($GETTEXT "Send message")
AVAILABLE=$($GETTEXT "Available chat IDs")
ENTER=$($GETTEXT "Enter text")
CONTINUE=$($GETTEXT "Continue?")

end () {
	exit 0
}

while true
do
	$DIALOG --menu Menu 10 8 4 list "$LIST" msg "$MSG" 2> /tmp/shellegram
	CHOICE=$(cat /tmp/shellegram)
	if [ "$CHOICE" == 'list' ]
	then
		if [ $# -ge 1 ]
		then
			IDS=$(echo "list" | $SHELLEGRAM | grep -o '[0-9]*') 
		else
			IDS=$($SHELLEGRAM list | grep -o '[0-9]*')
		fi
		$DIALOG --infobox "$IDS" 10 30 
		read WAIT
	elif [ "$CHOICE" == 'msg' ]
	then
		
		if [ $# -ge 1 ]
		then
		    IDS=$(echo "list" | $SHELLEGRAM | grep -o '[0-9]*' | awk '{print $1, $1}')
			$DIALOG --menu "$AVAILABLE" 10 30 10 $IDS 2> /tmp/shellegram
			CHOICE=$(cat /tmp/shellegram)
			echo $CHOICE
			TEXT=$($DIALOG --inputbox "$ENTER" 10 10 2>&1 >/dev/null)
			echo "$CHOICE|$TEXT" | $SHELLEGRAM 
		else
			IDS=$($SHELLEGRAM list | grep -o '[0-9]*' | awk '{print $1, $1}')
			$DIALOG --menu "$AVAILABLE" 10 30 10 $IDS 2>  /tmp/shellegram
			CHOICE=$(cat /tmp/shellegram)
			$DIALOG --inputbox "$ENTER" 10 10 2> /tmp/shellegram
			TEXT=$(cat /tmp/shellegram)
			$SHELLEGRAM msg $CHOICE "$TEXT"
		fi	
	fi

	$DIALOG --yesno $CONTINUE 10 10 || end

done


exit 0
