language: python

addons:
  apt:
    packages:
      - bash
      - dash
      - zsh

# Whatever the current shebang, replace with hardcoded shell
script: >
  sed -i '1s@.*@#!/usr/bin/env bash@' JSON.sh && ./all-tests.sh &&
  sed -i '1s@.*@#!/usr/bin/env zsh@'  JSON.sh && ./all-tests.sh &&
  sed -i '1s@.*@#!/usr/bin/env dash@' JSON.sh && ./all-tests.sh
